# Generated by Django 4.2.2 on 2023-06-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'ordering': ('sender', 'date_added')},
        ),
    ]
